<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/20
 * Time: 8:48
 */

namespace SYS_ADMIN\controllers\rest\v2;

use SYS_ADMIN\components\CommonHelper;
use SYS_ADMIN\components\ConStatus;
use SYS_ADMIN\models\Client;
use yii\rest\Controller;

class BaseController extends Controller
{
    public $user_info;
    public $isAdmin;
    public function init()
    {
        $debug = getenv('API_DEBUGE');
        parent::init(); // TODO: Change the autogenerated stub
        $base_url = \Yii::$app->request->getPathInfo();
        $action_name = str_replace('rest/v2/wechat/', '', $base_url);
        $action_name = str_replace('rest/v2/user/', '', $action_name);
        $action_name = trim($action_name, '/');
        $no_auth = ['jssdk', 'auth-login', 'notify', 'auth-login-back', 'add-menu', 'message', 'login'];
        // 校验参数
        if (\Yii::$app->request->isGet) {
            $params = \Yii::$app->request->get();
        } elseif (\Yii::$app->request->isPost) {
            $params = \Yii::$app->request->post();
        }

        if (!in_array($action_name, $no_auth)) {
            if (empty($params['signature']) || empty($params['timestamp'])) {
                return $this->errorInfo(ConStatus::$STATUS_ERROR_PARAMS, ConStatus::$ERROR_PARAMS_MSG);
            } else {
                $sign = $params['signature'];
                unset($params['signature']);
                ksort($params);
                if ($sign !== md5(ConStatus::$APP_KEY.implode($params)) || ($params['timestamp'] + 120) < time()) {
                    return $this->errorInfo(ConStatus::$STATUS_ERROR_PARAMS, ConStatus::$ERROR_PARAMS_MSG);
                }
            }
        }

        if (1 == $debug) { //调式模式
            $open_id = 'o5NW-52_GfBdOhc4nm2-Ggtardkg';
            $check_info = Client::findOne(['open_id' => $open_id]);
            $user_detail = [
                'user_name' => $check_info->client_name,
                'user_img' => $check_info->client_img,
                'open_id' => $check_info->open_id,
                'uid' => $check_info->id,
            ];
            $this->user_info = $user_detail;
        } else {
            if (strpos($base_url, 'client') != false) {
                $open_id = \Yii::$app->request->post('openid');
                if (empty($open_id) && !in_array($action_name, $no_auth)) {
                    return $this->errorInfo(ConStatus::$STATUS_ERROR_OPENID, ConStatus::$ERROR_CHECK_LOGIN_MSG);
                }

                $redis = \Yii::$app->redis;
                $user_info = $redis->get($open_id);
                if (empty($user_info) && !in_array($action_name, $no_auth)) {
                    return $this->errorInfo(ConStatus::$STATUS_ERROR_CHECK_LOGINOUT, ConStatus::$ERROR_CHECK_LOGINOUT_MSG);
                }

                $this->user_info = json_decode($user_info, true);
            }
        }

        $this->isAdmin = CommonHelper::isAdmin();
    }
    /**
     * 返回错误信息
     * {
     *   error: "请求参数有误。",
     *   message: "日志ID不能为空。",
     *   code: 4001,
     *   status: 400
     * }.
     */
    public function errorInfo($code, $extend_message = '')
    {
        $route = $this->action->controller->module->requestedRoute ?? '';
        $result = [
            'timestamp' => time(),
            'status' => 400,
            'error' => $code,
            'message' => is_array($extend_message) ? join("\n", $extend_message) : $extend_message,
            'code' => $code,
            'path' => $route,
        ];
        echo json_encode($result);
        exit;
    }

    /**
     * 返回成功的信息.
     *
     * @param array $data 返回的数据
     *
     * @return array
     */
    public function successInfo($data = [])
    {
        $result = [
            'timestamp' => time(),
            'status' => 200,
            'data' => $data,
        ];
        echo json_encode($result);
        exit;
    }
}